
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23

jdk:
  - oraclejdk8
  
before_script:
  # Start virtual frame buffer, see: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  ./gradlew check -PuiTest --info
