
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      language: android    
      addons:
        apt:
          packages:
            - xvfb
            - libgles2-mesa-dev
      android:
        components:
          - tools
          - tools
          - build-tools-28.0.3
          - platform-tools
          - android-28
      before_script:
        # Install the SDK
        - (while sleep 5; do echo "y"; done) | sdkmanager "platforms;android-27"
        # Start virtual frame buffer
        - "export DISPLAY=:99.0"
        - "/sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
        - sleep 3 # give xvfb some time to start
      script:
        ./gradlew check jacocoTestReport -PuiTest
      after_success:      
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      # xcode 9.3 includes jdk8
      osx_image: xcode9.3
      language: java
      before_install:
        # Download SDK
        - brew update --quiet
        - brew cask install android-sdk
        # Install the SDK
        - (while sleep 5; do echo "y"; done) | sdkmanager "platforms;android-28"
        - export ANDROID_HOME=/usr/local/share/android-sdk
      script:
        ./gradlew robovmArchive
