
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      language: android    
      addons:
        apt:
          packages:
            - xvfb
            - libgles2-mesa-dev
      android:
        components:
          - tools
          - tools
          - build-tools-26.0.2
          - platform-tools
          - android-25
      before_script:
        # Start virtual frame buffer
        - "export DISPLAY=:99.0"
        - "/sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
        - sleep 3 # give xvfb some time to start
      script:
        ./gradlew check jacocoTestReport -PuiTest --info
      after_success:      
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      language: java
      osx_image: xcode8.2
      jdk: openjdk8
      before_install:
        # Download SDK
        - brew update
        - brew cask install android-sdk
        # Install the SDK
        - (while sleep 5; do echo "y"; done) | sdkmanager "platforms;android-25"
        - export ANDROID_HOME=/usr/local/share/android-sdk
      script:
        ./gradlew robovmArchive
