
sudo: true

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      language: android    
      android:
        components:
          - tools
          - tools
          - build-tools-24.0.3
          - platform-tools
          - android-24
      before_script:
        # Start virtual frame buffer, see: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      script:
        ./gradlew check jacocoTestReport -PuiTest --info
      after_success:      
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      language: java
      osx_image: xcode8.2
      before_install:
        # Download SDK
        - brew install android-sdk
        # Install the SDK
        - android list sdk --all --extended
        - (while sleep 5; do echo "y"; done) | android update sdk --no-ui --all --filter tools,tools,build-tools-24.0.3,platform-tools,android-24
        - export ANDROID_HOME=/usr/local/opt/android-sdk
      script:
        ./gradlew robovmArchive
  allow_failures:
    - os: osx
