
sudo: true

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      language: android    
      android:
        components:
          - tools
          - tools
          - build-tools-24.0.3
          - platform-tools
          - android-24
      script:
        ./gradlew check jacocoTestReport -PuiTest --info
    - os: osx
      language: java
      osx_image: xcode8.2
      before_install:
        # Download SDK
        - brew install android-sdk
        # Install the SDK
        - android update sdk --no-ui
        - export ANDROID_HOME=/usr/local/opt/android-sdk
      script:
        ./gradlew robovmArchive -PuiTest --info
  allow_failures:
    - os: osx

before_script:
  # Start virtual frame buffer, see: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
  - bash <(curl -s https://codecov.io/bash)
