
language: android

matrix:
  include:
    - os: linux
      jdk:
        - oraclejdk8
    - os: osx
      osx_image: xcode8.2
  allow_failures:
    - os: osx
    
android:
  components:
    - tools
    - tools
    - build-tools-24.0.3
    - platform-tools
    - android-24

before_script:
  # Start virtual frame buffer, see: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  ./gradlew check jacocoTestReport -PuiTest --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
