# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
sass:
  load_paths:
    - _sass
plugins:
  - jekyll-feed

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NVList documentation
email: mail@weeaboo.nl
description: ''
url: "https://anonl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/nvlist" # the subpath of your site, e.g. /blog
repository: anonl/nvlist
exclude: [build]

collections:
  userguide:
    output: true
  lua:
    output: true

defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"
  - scope:
      type: "userguide"
    values:
      layout: "chapter"
      index: "/userguide.html"
  - scope:
      type: "lua"
    values:
      layout: "chapter"
      index: "/lua.html"

# These pages are linked in the header
header_pages:
  - userguide.html
  - lua.html

feed:
  collections:
    - userguide

# Exclude from processing.
#exclude:
#  - test.html
